### ISSUE TITLE
Sip doc doesn't work on fedora 40

### ISSUE THREAD

**Issue by Bombylius** [varqox/sim-project#26] opened 2024-09-04 09:14 UTC
When I run `sip doc` I get:
```
Compiling doc/statement.tex
Error: sandbox error: pid1: open_tree("/usr/share/texmf-dist/") - No such file or directory (os error 2)
```
I saw that this directory doesn't exist on my system, and that I have `texmf-dist` in `/usr/share/texlive/`.
When I tried adding `/usr/share/texlive/texmf-dist` and removing `/usr/share/texmf-dist/` in `sip_package.cc`, the compilation got further, but it gave the following error:
```
warning: kpathsea: configuration file texmf.cnf not found in these directories: /usr/bin:/usr/bin/share/texlive/texmf-local/web2c:/usr/bin/share/texlive/texmf-dist/web2c:/usr/bin/share/texlive/texmf/web2c:/usr/bin/texmf-local/web2c:/usr/bin/texmf-dist/web2c:/usr/bin/texmf/web2c:/usr:/usr/share/texlive/texmf-local/web2c:/usr/share/texlive/texmf-dist/web2c:/usr/share/texlive/texmf/web2c:/usr/texmf-local/web2c:/usr/texmf-dist/web2c:/usr/texmf/web2c:/usr/share/texmf-local/web2c:/usr/share/texlive:/usr/share/texlive/share/texlive/texmf-local/web2c:/usr/share/texlive/share/texlive/texmf-dist/web2c:/usr/share/texlive/share/texlive/texmf/web2c:/usr/share/texlive/texmf-local/web2c:/usr/share/texlive/texmf-dist/web2c:/usr/share/texlive/texmf/web2c.
This is pdfTeX, Version 3.141592653-2.6-1.40.25 (TeX Live 2023/Fedora 40) (preloaded format=pdflatex)

kpathsea: Running mktexfmt pdflatex.fmt
kpathsea: open("/dev/null", O_RDONLY): No such file or directory
I can't find the format file `pdflatex.fmt'!
doc/statement.tex: compilation failed
```
I checked the location of these files and got `/usr/share/texlive/texmf-dist/web2c/texmf.cnf` and `/var/lib/texmf/web2c/pdftex/pdflatex.fmt`. Both of which are in directories that are mounted, so I don't understand why they aren't found.

**Comment by varqox** [comment] 2024-09-04 23:06
Which distribution (and version) are you using? I want to reproduce the issue locally.

**Comment by Bombylius** [comment] 2024-09-05 21:06
Fedora 40, as mentioned in the title ;)

**Comment by varqox** [comment] 2024-09-11 20:58
It turned out, `sip doc` was broken everywhere for quite some time :(

The issue should be fixed by 4be81d777f0ec36b1bad30b683cca84f6e0a9576. Could you confirm? I will release it afterwards.

**Comment by marximimus** [comment] 2024-09-12 09:21
It works on Arch Linux ARM after the patch.

**Comment by Bombylius** [comment] 2024-09-12 12:54
Thanks, it works for me as well. By the way, could `sip doc` be made to work without putting `sim-statement.cls` it in `doc/`? I put it in `~/texmf/tex/latex/` and then could compile the tex file manually with pdflatex, but it isn't seen when compiling with `sip doc`.

**Comment by varqox** [comment] 2024-09-12 13:47
> Thanks, it works for me as well. By the way, could `sip doc` be made to work without putting `sim-statement.cls` in `doc/`? I put it in `~/texmf/tex/latex/` and then could compile the tex file manually with pdflatex, but it isn't seen when compiling with `sip doc`.

The problem is that the sim-statement.cls could change in an incompatible way in the future. Not requiring sim-statement.cls to be in the package would make sip doc fail for every package in the old format. Therefore I cannot opt for such change. For the same reason solutions, checker and generator need to be self-contained as well.

I strongly suggest creating packages that others will have no problem working with, so please leave sim-statement.cls in the package. It is for future compatibility (and makes possible compiling statement without sip and tweaking around with placing sim-statement.cls somewhere).

**Comment by varqox** [comment] 2024-09-12 13:48
> It works on Arch Linux ARM after the patch.

Oh, sip works on ARM, didn't expect that, but it is a good news :)

**Closed** 2024-09-12 13:49 UTC
