### ISSUE TITLE
Ranking takes ages to load

### ISSUE THREAD

**Issue by marximimus** [varqox/sim-project#35] opened 2024-10-30 09:07 UTC
https://sim.13lo.pl/c/c98#ranking

Sim’s other functions operate as expected, including rankings of other contests.

**Comment by efindus** [comment] 2024-11-01 10:21
It turns out that optimizing the submissions table alleviates the issue, thought in the long run it would IMO be beneficial to cache contest scores instead of calculating them on each request.

**Comment by varqox** [comment] 2024-11-01 12:39
The problem is a missing index that would make the ranking load fast - an old overlook. I will fix it shortly.

**Comment by varqox** [comment] 2024-11-01 13:04
Fixed in f66103bc4cb0540a7dac37d59b475650ea77fa0e.

**Closed by varqox** 2024-11-01 13:04 UTC
