### ISSUE TITLE
Failed to open: logs/job-server.log

### ISSUE THREAD

**Issue by marximimus** [varqox/sim-project#28] opened 2024-09-11 15:53 UTC
After installing sim with setup script for Debian 12, it prints the following error every second: `Failed to open: logs/job-server.log - no such file or directory (os error 2)`. I’ve fixed it by `touch`ing `subprojects/sim/sim/logs/job-server.log` (and `job-server-error.log`, which was also missing).

**Comment by varqox** [comment] 2024-09-15 19:19
Can you provide me the exact invocation of the setup script for Debian 12? I cannot reproduce it locally.

**Comment by marximimus** [comment] 2024-09-15 21:20
Adam will send it tomorrow.

**Comment by varqox** [comment] 2024-09-21 23:06
Fixed by 6bdb1caf03fa3b79b356b1a96b25e75175bc1374

**Closed by varqox** 2024-09-21 23:06 UTC
